services:
  mongo-demo:
    image: mongo
    container_name: mongo-demo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

    volumes:
      - mongo-demo:/data/db
    expose:
      - 27017
    ports:
      - '27017:27017'
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/admin",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  api-demo:
    build: ../
    container_name:  api-demo
    ports:
      - "8080:8080"  # Spring Boot app
      - "5005:5005"  # Debugging port
    links:
      - mongo-demo
    depends_on:
      mongo-demo:
        condition: service_healthy

volumes:
  mongo-demo: